name = "vpn"
main = "_worker.js"
compatibility_date = "2025-08-15"
workers_dev = false
preview_urls = false

kv_namespaces = [
  { binding = "PROXY_KV", id = "b5c49ca8fbd14c71af409ad0276ab0ec" }
]

routes = [
  { pattern = "vpn.ex27.my.id", custom_domain = true }
]

[unsafe.metadata.observability]
enabled = true

[observability]
enabled = true
head_sampling_rate = 1